### PR TITLE
Group 07 Hands-on assignment 1

### PR DESCRIPTION
**Pull request by anifledramos**

### CODE REVIEW

**Comment by ocorcho** [comment]
Assignments 2 and 3 are ok. Now @rgcmme to check the hands-on.

**Comment by rgcmme** [comment]
- The group directory must have a number, not XX
- Some of the deliverables are empty
- The hands-on must be in the domain of public procurement

**Comment by anifledramos** [comment]
Errors solved, sorry for the inconvenience, I was uploading work that was not done to my repository without realizing the pull request was still open.

**Comment by rgcmme** [comment]
The group directory is still named GroupXX.

**Comment by anifledramos** [comment]
It was already corrected in commit b6a3d89 (https://github.com/FacultadInformatica-LinkedData/Curso2020-2021-ODKG/pull/155/commits/b6a3d8952616d4b08b9b3892582dfc45e7842df1), in my repository it shows as Group07

**Comment by rgcmme** [comment]
True, I merge it.

**Pull request merged**
