### PR TITLE
Group07 Hands on assignments 7 and app

### PR DESCRIPTION
**Pull request by anifledramos**

### CODE REVIEW

**Comment by anifledramos** [comment]
Changed datasets from previous assignments

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
I'm not sure about what files should I review for assignment05.  Please, remove those files that I shouldn't review.

Anyway, I reviewed output-organizations-with-links.nt as and I found that you  defined triples like that:
<http://www.example.com/group07/organization/University%20of%20Amsterdam> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/name> but it is wrong because in schema.org doesn't exist such class. 
Thus, I reviewed your mapping-organizations-with-links.ttl:
- If you want to reuse schema.org vocabulary you have to check it carefully because schema:name, schema:street, schema:country, schema:city are not correct. E.g. schema:country should be schema:Country, schema:street doesn't exist, etc. 
- You have to check your mapping files because I saw the same errors.
- Now your RDF data with links doesn't follow your ontology. 

Finally, check carefully your queries because the triple patterns must be compliant with those triples from your RDF data. Your ontology doesn't have a <http://www.wikidata.org/entity/Organization> class thus your data neither.

**Comment by anifledramos** [comment]
Changes done. Our groupd changed datasets so we had to perform all tasks again, so we can't remove the past files from the pull request because we need them to be merged with our folder. However, we separated in commits the work to be evaluated so it could be easy to find it among the files. 

Files regarding assignments 5 and 6 should be on commit 64a6f23 and the missing yaml files are on commit 3c67184. Lastly, a clarification regarding csvs is added in commit 63c0bbd.

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Thanks for the explanation. 
Regarding Assignment 5, I have the following comments:
- The links that you defined are ok. 
- In the template-yarrrml-with-links.yml you are using ontology classes to define predicates. E.g. vocab:Country is defined as a predicate to configure the relation between Organization and Country mappings. However, vocab:Country is defined as a class in your ontology. Redefine the mapping and use the correct predicates (e.g. vocab:country). As you have these wrong definitions in your mapping, the output-with-links.nt file contains errors. Please, fix the mapping and generate the RDF data according to it. 
- Regarding queries, did you test that they get results back? Remember that these queries will be used in your application thus you will need that they work. I took a quick look at some of them but I see that it will not be possible to get the ones you are explaining in the text. e.g. query 5
Also, in these queries, you should use the classes and predicates that you used to generate your RDF data. Otherwise, you will not get results.

**Comment by ocorcho** [comment]
Links are ok, as commented by Paola.
RDF generated still suffers from some errors, as pointed out by Paola.
The grade for this part of the assignment is 6.5 out of 10 points.

**Pull request merged**
