### PR TITLE
Assigment 3 and Assigment 4

### PR DESCRIPTION
**Pull request by jagobazulu**

### CODE REVIEW

**Comment by jagobazulu** [comment]
Assigment 4

**Review by dachafra — CHANGES_REQUESTED** [review]
6.5: VCARD.Work does not exist in then ontology, change it please
task 7 also asks about to provide the same queries but using RDFlib only

**Comment by ocorcho** [comment]
Assignments 2 and 3 are ok.

**Comment by dachafra** [comment]
could you remove Assignment4/jagobazulu-20A257/.ipynb_checkpoints folder? 
rest ok

**Review by dachafra — APPROVED** [review]

**Pull request merged**
