### PR TITLE
Create Task06.ipynb

### PR DESCRIPTION
**Pull request by Sili-liu**

### CODE REVIEW

**Comment by dachafra** [comment]
Hi @Sili-liu could you include all the tasks in one PR?

**Comment by Sili-liu** [comment]
Sorry professor, This is my first time use GitHub, I know about I can use Git Bash or GitHubDesktop, but I don`t know how to do this. Last night I try to use GitHubDesktop,  but it`s look like doesn`t work.

**Comment by dachafra** [comment]
Hi, it actually worked, but you made 4 PR, 1 per each task. Try to close the other 3 and include in this all the tasks, please

**Comment by dachafra** [comment]
well done @Sili-liu, I'll now start with the review

**Review by dachafra — CHANGES_REQUESTED** [review]
Task06: are you sure that vcard:WorkAt exists??? vcard is an ontology already created, you cannot create new properties using its namespace
Task07 is incomplete, remember to take a look to the data you are loading to be sure that the answers are complete.
Task08: ok
Task09: you made the merge using FN property (FullName) not Given (http://www.w3.org/2001/vcard-rdf/3.0#Given ) and Family (http://www.w3.org/2001/vcard-rdf/3.0#Family) properties

**Review by dachafra — CHANGES_REQUESTED** [review]
task06: you are still using vcard:Work in 6.5, that property does not exist!!
task07: still has the same problems as before, look to the data and SPARQL slides
task09: still also have the same problem, where the definition of the task mentions the necessity of the use of FN property?? It says: "_We consider that two individuals are the same if they have the same nickname and family name."_

**Review by dachafra — APPROVED** [review]

**Comment by dachafra** [comment]
awesome work @Sili-liu! well done :-)

**Comment by Sili-liu** [comment]
Thank for helping.

**Pull request merged**
