### PR TITLE
anamarine-20A181 Assignment 4 task 06, 07

### PR DESCRIPTION
**Pull request by anamarine**
I don't know how to work with the namespaces from namespace_manager

### CODE REVIEW

**Comment by dachafra** [comment]
the title is assign4 but I only see .DS_Store files and modifications over Assignment1/DatasetDescriptions.csv

**Comment by anamarine** [comment]
I think now you should see them

**Comment by dachafra** [comment]
yes, task06 ok, task07 you need recursion to obtain all the data (take a look to the SPARQL slides and the data you are loading to understand it) and also the queries using RDFlib that are missing.

Remove from the PR .DS_Store files and the modifications over Assignment1/DatasetDescriptions.csv

**Review by dachafra — CHANGES_REQUESTED** [review]
yes, task06 ok, task07 you need recursion to obtain all the data (take a look to the SPARQL slides and the data you are loading to understand it) and also the queries using RDFlib that are missing.

Remove from the PR .DS_Store files and the modifications over Assignment1/DatasetDescriptions.csv

**Pull request closed without merging**
