### PR TITLE
Group 5 hands-on 6

### PR DESCRIPTION
**Pull request by dimnl**
This hands-on is a bit later as there was a misunderstanding; I hope this could still be taken into account with regard to the grade.

### CODE REVIEW

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
Links are ok, but you forgot to submit the SPARQL queries.

**Comment by dimnl** [comment]
The SPARQL queries were made again in Google Colab [here](https://colab.research.google.com/drive/1_pFdek35y1WFMgn-eEP1eOL1g-6GtnOj?usp=sharing). I will also upload the queries directly to this PR in some minutes.

**Comment by paoespinozarias** [comment]
No worries. You don't need to send it, they are ok!

**Comment by paoespinozarias** [comment]
Thanks! Please, @ocorcho review Hands-on 6.

**Review by paoespinozarias — APPROVED** [review]

**Pull request merged**
