### PR TITLE
Hands on assignment2 - Group01

### PR DESCRIPTION
**Pull request by eduayme**

### CODE REVIEW

**Comment by rgcmme** [comment]
The example file must also be in the turtle format

**Comment by eduayme** [comment]
@rgcmme true. I think we imported the example as a rdf syntax... Should we fix the example format and create a new MR?

**Comment by rgcmme** [comment]
You can fix it in this same pull request, You just perform the changes and the PR is updated.

**Comment by eduayme** [comment]
I think that if it is already merged this doesn't work. I will create a new PR.

**Comment by rgcmme** [comment]
Yes, I didn't noticed it was merged.

**Pull request merged**
