### PR TITLE
hands on assingment 1 Group10

### PR DESCRIPTION
**Pull request by RutgerBerghuis**

### CODE REVIEW

**Comment by rgcmme** [comment]
There is already a group 01. Please, change the number and start the name of the directory with a capital letter.

**Comment by RutgerBerghuis** [comment]
> There is already a group 01. Please, change the number and start the name of the directory with a capital letter.

Sorry for this. We divided all the group numbers in the group chat to not have this problem and we were supposed to be Group01. I changed to Group08 because it was still available in Github is this still available?

**Comment by rgcmme** [comment]
Yes, there is a group 8. You can check the groups here:

https://github.com/FacultadInformatica-LinkedData/Curso2020-2021-ODKG/tree/master/HandsOn

**Comment by rgcmme** [comment]
The is also a pull request for a group 9, so you can choose 10.

**Pull request merged**
