### PR TITLE
assignment 4 task 06 & 07

### PR DESCRIPTION
**Pull request by RutgerBerghuis**

### CODE REVIEW

**Review by dachafra — CHANGES_REQUESTED** [review]
6.5: g.add((ns.JohnSmith, VCARD.WorksFor, ns.UPM)) VCARD.WorksFor does not exist, change it by a valid property from VCARD or create a new one under your own namespace
7.1: results are not complete 
7 in general: queries have to be executed using only RDFlib

**Comment by RutgerBerghuis** [comment]
> 6.5: g.add((ns.JohnSmith, VCARD.WorksFor, ns.UPM)) VCARD.WorksFor does not exist, change it by a valid property from VCARD or create a new one under your own namespace
> 7.1: results are not complete
> 7 in general: queries have to be executed using only RDFlib

What do you mean by "7 in general: queries have to be executed using only RDFlib"? Is that not what i'm doing?

**Comment by dachafra** [comment]
noo... you are using SPARQL, there are functions (triples() value()) that allow you to query the data without using SPARQL

**Comment by RutgerBerghuis** [comment]
> noo... you are using SPARQL, there are functions (triples() value()) that allow you to query the data without using SPARQL

So i'm supposed to solve the exercise without the SPARQL queries? This confuses me because the exercise states "with RDFLib and SPARQL""and in the practice exercises it is solved like this.

**Comment by dachafra** [comment]
We're asking exactly the same as it is shown in tasks03 and task04, the queries are the same but are solved in two different ways

**Comment by RutgerBerghuis** [comment]
> We're asking exactly the same as it is shown in tasks03 and task04, the queries are the same but are solved in two different ways

Okay so i should not do it like it is done in task04 which i did now, but i should do it like its done in task03? Because i thought it had to be done like in task04 since the exercise states to use SPARQL.

**Comment by dachafra** [comment]
the task asks for providing both solutions

**Comment by RutgerBerghuis** [comment]
> the task asks for providing both solutions (see what your colleagues have been done)

Oh so i should provide both solutions. Sorry, this was not clear for me. Thank you for helping me!

**Review by dachafra — APPROVED** [review]

**Pull request merged**
