### PR TITLE
Assignment 5 and Assignment 6 Group 2

### PR DESCRIPTION
**Pull request by Lucasct77**

### CODE REVIEW

**Review by paoespinozarias — CHANGES_REQUESTED** [review]
First of all, I detected an error in your RDF data because the ontology classes are defined as strings instead of URIs. Please, fix it. Only the _Contrato_ class is well generated as a URI value in your data. 

Regarding the Linking process:
- Linking of _Publicorg_ and _Juntasmap_  instances is ok
- The links defined for the instances of _Distrito, Barrio, Provincia, and Localidad_ classes are ok, because we want to link them to same instances of Wikidata classes. However, _Distrito, Barrio, Provincia, and Localidad_  classes are not defined in your ontology version available in GitHub. Also, in your RDF data, the instances of these classes are not defined and are not related to any other instance. Please, check it and fix it.
- Query 1 uses properties (foaf:Localidad or foaf:name) that are not defined in your ontology and that your RDF data doesn't have.

**Comment by Lucasct77** [comment]
Good afternoon,

We have been working on the comments you posted, correcting the undeclared classes and removing the empty rows from the rdf

**Review by paoespinozarias — COMMENTED** [review]
Good morning, 

Regarding your updates of Assignment 5:
- The ontology now contains the classes that were missing in your last submission. Thus, the linking is ok. However, in template-yarrrml-with-links-updated.yml the owl prefix definition is wrong. Its URI ends in a # instead of / 
- Regarding the SPARQL Queries in the queries-with-links.sparql file:
  Query 1 contains foaf predicates, it uses FROM clause to ns??? Please, fix it. 
  The owl prefix definition contains a mistake. (Its URI ends in a # instead of / )
  The ns prefix doesn't match your ontology URI.
  Update the other queries to follow the predicates stated in your ontology and your RDF data. (Please, also update the ones in the queries.sparql file)

Finally, fix the definition of your class instances in your actividad_contractual-with-links.ttl file. E.g. the Contractee classs in this instance <http://MadridPublicContracts/ontology/B37511128> <http://www.w3.org/1999/02/22-rdf-syntax-ns/type> "http://MadridPublicContracts/ontology/Contractee" still is generated as a string instead of a URI -> <http://MadridPublicContracts/ontology/Contractee>. 
The same happens in the last version of actividad_contractual-updated.ttl -> <http://MadridPublicContracts/resources/contractee/B82917063> <http://www.w3.org/1999/02/22-rdf-syntax-ns/type> "http://purl.org/procurement/public-contracts#Tender".

**Comment by ocorcho** [comment]
Generated RDF is almost correct, as pointed out by Paola. Links are ok as well, although we understand the difficulty of finding too many links in this context. The use of PPROC is not complete, with some properties that you needed to add that were really in the ontology, although this required a further understanding. 
You obtain a grade of 7.5 over 10 in this part of the evaluation

**Comment by Lucasct77** [comment]
Good afternoon,

Thank you for reviewing the changes and feedback.

We have added the corrections to Paola's comments. 

We will look again at PPROC in case we see any more properties that we can add.

Thank you

**Review by paoespinozarias — APPROVED** [review]
Good afternoon,
Most of the changes that I suggested were addressed. However, be careful with the first query in queries-with-links.sparql file since it uses foaf predicates that are not included in your ontology and in your RDF data neither.

**Pull request merged**
