### PR TITLE
assigment4 - Fcabla - 20A268

### PR DESCRIPTION
**Pull request by Fcabla**

### CODE REVIEW

**Review by dachafra — CHANGES_REQUESTED** [review]
task06: ok
task07: the queries have to be provided also using only RDFlib functions
7.1. you are asking about all subclasses, that is not correct, the query has to ask about the subclasses of person
7.2 and 7.3 are not correct, a similar issue as in 7.1
8:  you have to find in g2 triples with properties (given name, family name and email) and add those triples to g1

**Comment by dachafra** [comment]
okey, tas07 is now correct but you have to provide also the same solutions using only the search functions of RDFlib (triples and value)

**Comment by dachafra** [comment]
fantastic! well done @Fcabla

**Comment by rgcmme** [comment]
Rename the hands-on directory from "Grupo 06" to "Group06"

**Pull request merged**
