### PR TITLE
Assignment 4 - Task06 and Task07

### PR DESCRIPTION
**Pull request by TeresaGCG**

### CODE REVIEW

**Comment by dachafra** [comment]
Almost perfect, where did you see that vcard:Works exists? ;-)

**Review by dachafra — CHANGES_REQUESTED** [review]
review vcard:Works property please, thanks for pointing out the RDFS property typo!

**Comment by dachafra** [comment]
why did you close the PR?

**Comment by TeresaGCG** [comment]
Since I have fixed Task06, I'm going to open a new PR. Is there any way to change the files in this one? I couldn't find how to do it. Also, I've already finished Task08 so I want to add it to the PR.

**Comment by dachafra** [comment]
Changes are actually added to this PR (when you have an open PR to another repository you can add new commits to it if it is still open). See that in this conversation your changes have appeared (figure), so we can reopen the PR and if all is correct I can accepted it
image

**Review by dachafra — CHANGES_REQUESTED** [review]
You have used vcard:Org but should be vcard:org, capital letters are only used for classes and in this case, vcard:org exists but must be lower case as it is a property, change it and I'll accept it

**Comment by TeresaGCG** [comment]
Thank you for your help

**Comment by dachafra** [comment]
@TeresaGCG awesome work! well done

**Pull request merged**
